services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    env_file:
      - ./databases/mongo/.env
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
