services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    env_file:
      - ./databases/mongo/.env
    volumes:
      - mongo_data:/data/db

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./frontend/build:/var/www/html

volumes:
  mongo_data:
